/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'm.karmazyn' at '7/6/15 3:41 PM' with Gradle 2.3
 *
 * @author m.karmazyn, @date 7/6/15 3:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
